name: Airflow Lint DAGs

on:
  push:
    paths:
      - 'dags/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-verison: [3.6]
      fail-fast: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Install Airflow and Lint
      run: |
        python3 -m pip install apache-airflow[all] pylint pylint-airflow
        pylint --load-plugins=pylint_airflow dags

